### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by jakubdonovan** [cloudinary/cloudinary-svelte#10]
## Bug report for Cloudinary Svelte SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
> self is not defined
> ReferenceError: self is not defined
>     at eval (/node_modules/@cloudinary/svelte/dist/index.umd.js:3:208)
>     at eval (/node_modules/@cloudinary/svelte/dist/index.umd.js:3:242)
>     at instantiateModule (file:///Users/jakubdonovan/Documents/code/shieldprotocol/node_modules/vite/dist/node/chunks/dep-665b0112.js:53333:15)

## Issue Type (Can be multiple)
app breaks as soon as I uncomment
`import { Image } from '@cloudinary/svelte';`

## Steps to reproduce
`import { Image } from '@cloudinary/svelte';`

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[x] All

## Versions and Libraries (fill in the version numbers)
Cloudinary - "@cloudinary/svelte": "^1.0.0-beta.11",
SvelteKit - "svelte": "^3.44.0",

**Comment by tamaracloudinary** [comment]
Hey @jakubdonovan , Could you elaborate on where are you trying to import these modules? I'm asking because `self` is probably referring to the `window` object, which is [only relevant on the front end](https://stackoverflow.com/a/46940797). Could you try importing them at one of your front-end files? (possibly one of your React components)

**Comment by jakubdonovan** [comment]
> Hey @jakubdonovan , Could you elaborate on where are you trying to import these modules? I'm asking because `self` is probably referring to the `window` object, which is [only relevant on the front end](https://stackoverflow.com/a/46940797). Could you try importing them at one of your front-end files? (possibly one of your React components)

Hey, I'm importing it into one of my svelte components
<img width="632" alt="Screenshot 2022-11-20 at 21 16 42" src="https://user-images.githubusercontent.com/16073448/202907229-a5769771-11c8-4dc4-a2b5-3ecadafccba3.png">

**Comment by tamaracloudinary** [comment]
What version are you using? maybe you are trying to render your component on the server?
if that's the case, you can try this code: 

` let initLiveStream, attachCamera, detachCamera

  useEffect(() => {
    if(typeof window !== undefined){
      const Cloudinary = require('@cloudinary/js-streaming');
      initLiveStream = Cloudinary.initLiveStream;
      attachCamera = Cloudinary.attachCamera;
      detachCamera = Cloudinary.detachCamera;
    }
  }, [])`

You can also take a look at this svelte example:
https://codesandbox.io/s/bhupi?file=/App.svelte

**Comment by jakubdonovan** [comment]
> What version are you using? maybe you are trying to render your component on the server? if that's the case, you can try this code:
> 
> ` let initLiveStream, attachCamera, detachCamera
> 
> useEffect(() => { if(typeof window !== undefined){ const Cloudinary = require('@cloudinary/js-streaming'); initLiveStream = Cloudinary.initLiveStream; attachCamera = Cloudinary.attachCamera; detachCamera = Cloudinary.detachCamera; } }, [])`
> 
> You can also take a look at this svelte example: https://codesandbox.io/s/bhupi?file=/App.svelte

I use `"@cloudinary/svelte": "^1.0.0-beta.11",` The problem is that my application breaks as soon as I import the module, before I even try to use the component to pull any images from cloudinary

**Comment by jakubdonovan** [comment]
> What version are you using? maybe you are trying to render your component on the server? if that's the case, you can try this code:
> 
> ` let initLiveStream, attachCamera, detachCamera
> 
> useEffect(() => { if(typeof window !== undefined){ const Cloudinary = require('@cloudinary/js-streaming'); initLiveStream = Cloudinary.initLiveStream; attachCamera = Cloudinary.attachCamera; detachCamera = Cloudinary.detachCamera; } }, [])`
> 
> You can also take a look at this svelte example: https://codesandbox.io/s/bhupi?file=/App.svelte

I have created a minimal repo reproducing the error.
https://github.com/jakubdonovan/cloudinary-svelte-minimal
<img width="1151" alt="Screenshot 2022-11-22 at 12 38 25" src="https://user-images.githubusercontent.com/16073448/203233461-5915fee9-fd55-432a-8ae7-64806b694de2.png">

**Comment by PixelCook** [comment]
<img width="804" alt="Screen Shot 2022-11-24 at 16 37 50" src="https://user-images.githubusercontent.com/71414229/203809977-dad38ff5-1a6e-454c-b33b-5a937bee8752.png">

Trying to recreate your error has been unsuccessful. Have you tried npm i cloudinary, npm i @cloudinary/url-gen, npm install to make sure you have all dependencies?

**Comment by jakubdonovan** [comment]
> npm i @cloudinary/url-gen

I just tried with the dependency you mentioned even though it is not mentioned anywhere in the cloudinary svelte component's documentation, to no success. And since I can see that you have tried to run it in preview mode rather than in development, I have also tried the same and was once again unsuccessful. 
https://github.com/jakubdonovan/cloudinary-svelte-minimal
`npm run dev`

https://www.loom.com/share/b88bfd1368b044309ffe897825040346

**Comment by epasos573** [comment]
Hi Jakub,

Checking on the package.json of your sample project, it seems that the `cloudinary-core` is not yet installed in your environment:

`npm install cloudinary-core`

**Comment by jakubdonovan** [comment]
> npm install cloudinary-core]

I just installed it but that did not fix the issue
<img width="1279" alt="Screenshot 2022-11-27 at 06 24 40" src="https://user-images.githubusercontent.com/16073448/204112455-96518780-bd5a-40dd-9164-ab0f8dbc0573.png">

**Comment by tamaracloudinary** [comment]
Hi Jakub, 

I cloned your repo and could recreate the problem, I fixed it with:

1. `npm install svelte-cloudinary`
2. I pasted this entire piece of code in `+page.svelte` instead of `import { Image } from 'svelte-cloudinary'` (which is wrong because it is supposed to be an image with a lowercase i):

```

<script>

  import { image, initialize } from 'svelte-cloudinary'

  initialize({ cloud_name: 'myCloudinaryCloud' })

  const src = 'my/cloudinary/asset'
</script>

<style>
  img {
    width: 50vw;
    height: 50vh;
    object-fit: cover;
  }
</style>

<img
  use:image={{ src, bind: true, lazy: true }}
  class="home-img"
  alt="background" />
```

<img width="1512" alt="Screen Shot 2022-11-27 at 17 22 31" src="https://user-images.githubusercontent.com/98945360/204143322-e3413583-7db1-4fde-a7dc-0637a31e581c.png">

**Comment by jakubdonovan** [comment]
> Hi Jakub,
> 
> I cloned your repo and could recreate the problem, I fixed it with:
> 
> 1. `npm install svelte-cloudinary`
> 2. I pasted this entire piece of code in `+page.svelte` instead of `import { Image } from 'svelte-cloudinary'` (which is wrong because it is supposed to be an image with a lowercase i):
> 
> ```
> 
> <script>
> 
>   import { image, initialize } from 'svelte-cloudinary'
> 
>   initialize({ cloud_name: 'myCloudinaryCloud' })
> 
>   const src = 'my/cloudinary/asset'
> </script>
> 
> <style>
>   img {
>     width: 50vw;
>     height: 50vh;
>     object-fit: cover;
>   }
> </style>
> 
> <img
>   use:image={{ src, bind: true, lazy: true }}
>   class="home-img"
>   alt="background" />
> ```
> 
> <img alt="Screen Shot 2022-11-27 at 17 22 31" width="1512" src="https://user-images.githubusercontent.com/98945360/204143322-e3413583-7db1-4fde-a7dc-0637a31e581c.png">

The integration you have used is not the official one that I have used. 
https://www.npmjs.com/package/@cloudinary/svelte

**Comment by tamaracloudinary** [comment]
Hi @jakubdonovan, 
Good on you for noticing this, and sorry for the confusion!
 
I managed to recreate the issue and escalated this to our dev team. 
We suspect this is a specific issue with vite, but we need more time to investigate. 

I will keep you posted with every new info we get.
Thank you for your patience!
-Tamara

**Comment by jakubdonovan** [comment]
> 

Thank you

**Comment by tamaracloudinary** [comment]
Hi @jakubdonovan, we don't support svelte anymore, thus this issue will not be solved. 
You can use one of our other SDKs: https://cloudinary.com/documentation/cloudinary_sdks
Thanks for understanding!
Tamara
